In [ ]:
#chatgpt
!pip install -q flair
import flair
from flair.models import SequenceTagger
from flair.data import Sentence


tagger = SequenceTagger.load(
    "stefan-it/hmbench-ajmc-en-hmbert-bs8-wsFalse-e10-lr5e-05-poolingfirst-layers-1-crfFalse-3"
)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 52.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 62.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 15.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.1/203.1 kB 21.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 103.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.9 MB/s eta 0:00:00
  Building wheel for langdetect (setup.py) ... done
  Building wheel for pptree (setup.py) ... done
  Building wheel for sqlitedict (setup.py) ... done
  Building wheel for wikipedia-api (setup.py) ... done
  Building wheel for docopt (setup.py) ... done

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

2026-01-14 03:19:21,433 SequenceTagger predicts: Dictionary with 25 tags: O, S-scope, B-scope, E-scope, I-scope, S-pers, B-pers, E-pers, I-pers, S-work, B-work, E-work, I-work, S-loc, B-loc, E-loc, I-loc, S-date, B-date, E-date, I-date, S-object, B-object, E-object, I-object

In [ ]:
import pandas as pd

In [ ]:
import spacy

In [ ]:
nlp = spacy.load("en_core_web_sm", disable=["ner", "parser", "lemmatizer"])
nlp.add_pipe("sentencizer")

In [ ]:
def sent_full_text(text):
  doc= nlp(text)
  sentences = []
  for sent in doc.sents:
    s=sent.text
    sentences.append(s)
  return sentences

In [ ]:
lives = pd.read_csv("/content/lives_books.csv")

In [ ]:
lives["sent_full_text"]=lives["Text"].apply(sent_full_text)

In [ ]:
lives.iloc[3]['sent_full_text'][0]

'   I. With regard to Lykurgus the lawgiver there is nothing whatever that is undisputed; as his birth, his travels, his death, and, besides all this, his legislation, have all been related in various ways; and also the dates of his birth do not in any way accord.'

In [ ]:
lives = lives.drop(columns={"Text"})

In [ ]:
lives

,Unnamed: 0,X,Title,Text
0,2,2,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci..."
1,3,3,LIFE OF ROMULUS.,Historians are not agreed upon the origin a...
2,4,4,COMPARISON OF THESEUS AND ROMULUS.,I. The above are all the noteworthy particu...
3,5,5,LIFE OF LYKURGUS.,I. With regard to Lykurgus the lawgiver the...
4,6,6,LIFE OF NUMA.,I. There is a considerable conflict of opin...
...,...,...,...,...
63,65,65,COMPARISON OF DION AND BRUTUS.,I. Among the glories of these two men's liv...
64,66,66,LIFE OF ARTAXERXES.,"I. The first Artaxerxes, who surpassed all ..."
65,67,67,LIFE OF ARATUS.,"I. It seems to me, my Polykrates, that it w..."
66,68,68,LIFE OF GALBA.,I. The Athenian general Iphikrates thought ...
67,69,69,LIFE OF OTHO.,I. The young emperor[629] proceeded at dayb...

In [ ]:
full_sents_exp = lives.explode("sent_full_text")

In [ ]:
full_sents_exp.to_csv("/content/drive/MyDrive/DaD_2026/full_sents.csv")

In [ ]:
#chat
def split_into_sentences(text, max_chars=500):
    doc = nlp(text)
    sentences = []
    for sent in doc.sents:
        s = sent.text.strip()
        if len(s) > max_chars:
            # hard fallback split
            chunks = [s[i:i+max_chars] for i in range(0, len(s), max_chars)]
            sentences.extend(chunks)
        else:
            sentences.append(s)
    return sentences

In [ ]:
lives["sent_lim"]=lives["Text"].apply(split_into_sentences)

In [ ]:
lives= lives.drop(columns={"Text"})

In [ ]:
lives1 = lives.explode("sent_lim")

In [ ]:
lives1.to_csv("/content/drive/MyDrive/DaD_2026/sent_lims.csv")

In [ ]:
test = pd.read_csv("/content/drive/MyDrive/unexploded.csv")

In [ ]:
test = test.drop(columns={"Text"})

In [ ]:
type(test["sent_full_text"][0])

str

In [ ]:
lives["sent_full_text"]=lives["Text"].apply(sent_full_text)

In [ ]:
lives["sent_token_lims"]=lives["Text"].apply(split_into_sentences)

In [ ]:
lives.iloc[50]["sent_full_text"][1]

' These verses really represent the state of those who, in order to obtain the empty title of statesmen and popular leaders, govern a country by following the caprices and impulses of the people.'

In [ ]:
lives.iloc[50]["sent_token_lims"][2]

'These verses really represent the state of those who, in order to obtain the empty title of statesmen and popular leaders, govern a country by following the caprices and impulses of the people.'

In [ ]:
lives = lives.drop(columns={"Unnamed: 0","X"})

In [ ]:
exploded_df = lives.explode("sent_token_lims")

In [ ]:
beep = exploded_df[exploded_df['Title']=="LIFE OF C."]

In [ ]:
beep.iloc[1]["sent_full_text"][2]

"The cause of the enmity between Cæsar and Sulla was Cæsar's relationship to Marius; for the elder Marius was the husband of Julia the sister of Cæsar's father, and Julia was the mother of the younger Marius, who was consequently Cæsar's cousin."

In [ ]:
beep

,Unnamed: 0,X,Title,Text,sent_full_text,sent_token_lims
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...",CÆSAR.
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...",I.[435] When Sulla got possession of the supre...
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...",The cause of the enmity between Cæsar and Sull...
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...",Cæsar was not content with being let alone by ...
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...",But Sulla by his opposition contrived to exclu...
...,...,...,...,...,...,...
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...",Shakspere may have meant to represent Brutus a...
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...","The ""great dæmon"" of Cæsar avenged him on his ..."
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...","Brutus dies like a Roman, and that murder to w..."
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...","But if the play is faulty in construction, as ..."
47,49,49,LIFE OF C.,CÆSAR. I.[435] When Sulla got possession of...,"[ CÆSAR., I.[435] When Sulla got possession ...",

In [ ]:
len(beep["sent_token_lims"])

1633

In [ ]:
len(beep[])

In [ ]:
exploded_df.iloc[2000]["sent_full_text"]

['   I. As a parallel to Solon we shall take Poplicola, who was honoured with this name by the Romans, his original name having been Publius Valerius, a supposed descendant of that Valerius who in ancient times was especially instrumental in making the Romans and Sabines cease to be enemies and become one people; for it was he who persuaded the two kings to meet and make terms of peace.',
 'Valerius, a descendant of this hero, was a man of eminence in Rome, which was then ruled by the kings, because of his eloquence and wealth.',
 'He always spoke boldly on the side of justice, and assisted the poor and needy with such kindness that it was clear that, in case of a revolution, he would become the first man in the state.',
 ' Tarquinius Superbus, the king, had not come to his throne justly, but by wicked and lawless violence, and as he reigned tyrannically and insolently, the people hated him, and seized the opportunity of the death of Lucretia, after her dishonour, to drive him out.',
 'Lucius Brutus, who was determined to change the form of government, applied to Valerius first of all, and with his vigorous assistance drove out the king.',
 "After these events Valerius kept quiet, as long as it seemed likely that the people would choose a single general to replace their king, because he thought that it was Brutus's right to be elected, as he had been the leader of the revolution.",
 'However the people, disgusted with the idea of monarchy, and thinking that they could more easily endure to be ruled by two men, proposed that two consuls should be chosen.',
 'Valerius now became a candidate, hoping that he and Brutus would be elected; but he was not chosen.',
 'Brutus, instead of Valerius, whom he would have preferred, had as a colleague Tarquinius Collatinus, the husband of Lucretia, who was not a better man than Valerius, but was elected because the men in power at Rome, seeing what intrigues the exiled king was setting on foot to secure his return, wished to have for their general a man who was his sworn personal enemy.',
 ' II.',
 "Valerius, disgusted at the idea that he was not trusted to fight for his country because he had not suffered any personal wrong at the hands of the king, left the senate, refused to attend public meetings, and ceased to take any part whatever in public affairs, so that people began to fear that in his rage he might go over to the king's party and destroy the tottering edifice of Roman liberty.",
 'Brutus suspected some others besides him, and proposed on a certain day to hold a solemn sacrifice and bind the senate by an oath.',
 'Valerius, however, came cheerfully into the Forum, and was the first to swear that he would never yield anything to the Tarquins, but would fight for liberty to the death, by which he greatly delighted the senate and encouraged the leading men of the state.',
 'His acts too, immediately confirmed his words, for ambassadors came from Tarquin with specious and seductive proposals, such as he thought would win over the people, coming from a king who seemed to have laid aside his insolence and only to wish for his just rights.',
 'The consuls thought it right that these proposals should be laid before the people, but Valerius would not permit it, not wishing that the poorer citizens, to whom the war was a greater burden than the monarchy had been, should have any excuse for revolt.',
 ' III.',
 'After this came other ambassadors, announcing that Tarquin would give up his throne, put an end to the war, and only ask for his own property and that of his relatives and friends, upon which to live in exile.',
 'Many were inclined to agree to this, and amongst them Collatinus, when Brutus, an inflexible and harsh-tempered man, rushed into the Forum, calling out that his colleague was a traitor, who wished to furnish the tyrant with the means of continuing the war and recovering his throne, when he ought rather to grudge him food to keep him from starving.',
 'The citizens assembled, and Caius Minucius, a private citizen, was the first man who addressed them, encouraging Brutus, and pointing out to the Romans how much better it was that the money should be used to help them than to help their enemies.',
 'In spite of this, however, the Romans decided that, as they now possessed the liberty for which they had fought, they would not lose the additional blessing of peace for the sake of this property, but would cast it from them after the tyrant to which it belonged.',
 ' Tarquin really cared little for the property, and the demand was merely made in order to sound the people and arrange a plot for the betrayal of the state, which was managed by the ambassadors whom he had nominally sent to look after his property.',
 'These men were selling some part of it, keeping some safe, and sending some of it away, and meanwhile intrigued so successfully that they won over two of the best families in Rome, that of the Aquillii, in which were three senators, and that of the Vitellii, among whom were two.',
 "All these men were, on the mother's side, nephews of the consul Collatinus, and the Vitellii were also related to Brutus, for he had married their sister, and by her had a large family.",
 "The Vitellii, being relatives and intimate friends of the two elder sons of Brutus, induced them to take part in the conspiracy, holding out to them the hope that they might ally themselves to the great house of Tarquin, soon to be restored to the throne, and would rid themselves of their father's stupidity and harshness.",
 'By harshness, they alluded to his inexorable punishment of bad men, and the stupidity was that which he himself affected for a long time, in order to conceal his real character from the tyrant, which was made matter of reproach to him afterwards.',
 ' IV.',
 'So, after they had persuaded these young men, they conferred again with the Aquillii, and determined that all the conspirators should swear a great and terrible oath, in which a man is killed, and each person then pours a libation of his blood, and touches his entrails.',
 'The room in which they meant to do this was, as may be supposed, a dark and half-ruined one.',
 'Now a servant of the name of Vindicius happened to conceal himself in it; not that he had any designs or any knowledge of what was going on, but chancing to be in the room when the conspirators solemnly entered, he was afraid of being detected there, and so hid himself behind a chest, where he could see what was done and hear what was said by them.',
 'They agreed to assassinate both consuls, and wrote a letter to Tarquin acquainting him with their determination, which they gave to the ambassadors, who were lodging in the house of the Aquillii as their guests, and were present at this scene.',
 'After this they dispersed, and Vindicius came out from his hiding-place.',
 'He was at a loss what use to make of the discovery which Fortune had thrown in his way, for he thought it a shocking thing, as indeed it was, for him to make such a fearful revelation to Brutus about his sons, or to Collatinus about his nephews, and he would not trust any private citizen with a secret of such importance.',
 "Tormented by his secret, and unable to remain quiet, he addressed himself to Valerius, chiefly moved to do so by his affable kindly temper; for his house was open all day to those who wished to speak with him, and he never refused an interview or rejected a poor man's petition.",
 ' V. When, then, Vindicius came before him and told him all that he knew in the presence only of his wife and his brother Marcus, Valerius was astounded and horrified.',
 "He would not let the man go, but locked him up, set his wife to guard the door, and bade his brother to surround the king's quarters, to seize the letter, if possible, keeping a strict watch over all the servants there.",
 'He himself, with a large train of clients, friends and servants, went to the house of the Aquillii, who were not within.',
 "As no one expected him, he pushed into the house and found the letter lying in the ambassadors' apartments.",
 ' While he was thus employed, the Aquillii returned in haste, and assembling a force at the door endeavoured to take away the letter from him.',
 'His own party came to his assistance, and with their gowns twisted round their necks with much buffeting made their way to the Forum.',
 "The same thing happened at the king's quarters, where Marcus laid hold of another letter which was being taken thither concealed among some baggage, and brought as many of the king's party as he could into the Forum.",
 ' VI.',
 "When the consuls had put a stop to the confusion, Vindicius, at Valerius's command, was brought out of his prison, and a court was held.",
 'The letters were recognised, and the culprits had nothing to say for themselves.',
 'All were silent and downcast, and a few, thinking to please Brutus, hinted at banishment as the penalty of their crime.',
 'Collatinus by his tears, and Valerius by his silence gave them hopes of mercy.',
 'But Brutus, addressing each of his sons by name, said, "Come, Titus, come Tiberius, why do you make no answer to the charges against you?"',
 'As, after being asked thrice, they made no answer, he, turning his face to the lictors, said, "I have done my work, do yours."',
 'They immediately seized upon the young men, tore off their clothes, tied their hands behind their backs, and scourged them.',
 'Although the people had not the heart to look at so dreadful a sight, yet it is said that Brutus never turned away his head, and showed no pity on his stern countenance, but sat savagely looking on at the execution of his sons until at last they were laid on the ground and their heads severed with an axe.',
 'Then he handed over the rest of the culprits to be dealt with by his colleague, rose, and left the Forum.',
 'His conduct cannot be praised, and yet it is above censure.',
 'Either virtue in his mind overpowered every other feeling, or his sorrow was so great as to produce insensibility.',
 'In neither case was there anything unworthy, or even human in his conduct, but it was either that of a god or a brute beast.',
 'It is better, however, that we should speak in praise of so great a man rather than allow our weakness to distrust his virtue.',
 'Indeed the Romans think that even the foundation of the city by Romulus was not so great an event as the confirmation of its constitution by Brutus.',
 ' VII.',
 'When he left the Forum all men were silent for a long while, shuddering at what had been done.',
 'The Aquillii took heart at the mildness of Collatinus, and asked for time to prepare their defence.',
 'They also begged that Vindicius might be given up to them, because he was their servant, and ought not to be on the side of their accusers.',
 'Collatinus was willing to allow this, but Valerius said that he was not able to give the man up, because he was surrounded by so large a crowd, and called upon the people not to disperse without punishing the traitors.',
 'At last he laid his hands upon the two corpses, called for Brutus, and reproached Collatinus for making his colleague act against nature by condemning his own sons to death, and then thinking to please the wives of these traitors and public enemies by saving their lives.',
 'The consul, vexed at this, ordered the lictors to seize Vindicius.',
 'They forced their way through the crowd, tried to lay hold of him, and struck those who defended him, but the friends of Valerius stood in front of him and beat them off, and the people raised a shout for Brutus.',
 'He returned, and when silence was restored said that he had, as a father, full power to condemn his sons to death, but that as for the other culprits, their fate should be decided by the free vote of the citizens, and that any one might come forward and address the people.',
 'The people, however, would listen to no speeches, but voted unanimously for their death, and they were all beheaded.',
 ' Collatinus, it seems, had been viewed with suspicion before because of his connection with the royal family, and his second name, Tarquinius, was odious to the people.',
 'After these events, having utterly failed as consul, he voluntarily laid down that office, and left the city.',
 'So now there was another election, and Valerius received the due reward of his patriotism and was gloriously made consul.',
 'Thinking that Vindicius ought to receive something for his services, he made him a freedman, the first ever made in Rome, and allowed him to vote in whatever tribe he chose to be enrolled.',
 'The other freedmen were not allowed the suffrage till, long after, it was given them by Appius to obtain popularity among them.',
 'The whole ceremony is up to the present day called _vindicta_, after Vindicius, we are told.',
 ' VIII.',
 "After this they allowed the king's property to be plundered, and destroyed the palace.",
 'Tarquinius had obtained the pleasantest part of the Field of Mars, and had consecrated it to that god.',
 'This field had just been cut, and the corn lay on the ground, for the people thought that they must not thresh it or make any use of it, because of the ground being consecrated, so they took the sheaves and threw them into the river.',
 'In the same way they cut down the trees and threw them in, leaving the whole place for the god, but uncultivated and unfruitful.',
 'As there were many things of different sorts all floating together in the river, the current did not carry them far, but when the first masses settled on a shallow place, the rest which were carried down upon them could not get past, but became heaped up there, and the stream compacted them securely by the mud which it deposited upon them, not only increasing the size of the whole mass, but firmly cementing it together.',
 'The waves did not shake it, but gently beat it into a solid consistency.',
 'Now, from its size, it began to receive additions, as most of what the river brought down settled upon it.',
 'It is now a sacred island close by the city, with temples and walks, and in the Latin tongue it has a name which means "between two bridges."',
 "Some state that this did not happen when Tarquinia's field was consecrated, but in later times when Tarquinia gave up another field next to that one, for the public use.",
 'This Tarquinia was a priestess, one of the Vestal virgins, and she was greatly honoured for having done so, and was allowed to appear as a witness in court, which no other woman could do; she also was permitted to marry, by a decree of the senate, but did not avail herself of it.',
 'These are the legends which they tell about this island.',
 ' IX.',
 'Tarquin now gave up all hopes of recovering his throne by intrigue, and appealed to the Etruscans, who willingly espoused his cause and endeavoured to restore him with a great army.',
 'The consuls led out the Romans to fight against them, posting them in holy places one of which is called the Arsian grove, and another the Aesuvian meadow.',
 'When they were about to join battle, Aruns, the son of Tarquin, and Brutus, the Roman consul, attacked one another, not by chance, but with fell hatred and rage, the one urging his horse against the tyrant and enemy of his country, the other against the man who drove him into exile.',
 'Falling upon one another with more fury than judgment, they made no attempt to defend themselves, but only to strike, and both perished.',
 'The struggle, so terribly begun, was continued with equal ferocity on both sides, until the armies, after great losses, were separated by a tempest.',
 'Valerius was in great straits, not knowing how the battle had gone, and observing that his soldiers were despondent when they looked at the corpses of their comrades, and elated when they saw those of the enemy, so equal and undecided had been the slaughter.',
 'Yet each side, when it viewed its own dead close by, was more inclined to own itself defeated, than to claim the victory because of the supposed losses of the enemy.',
 'Night came on, and it was spent as may be imagined by men who had fought so hard.',
 'When all was quiet in both camps, we are told that the grove was shaken, and that from it proceeded a loud voice which declared that the Etruscans had lost one man more than the Romans.',
 'Apparently it was the voice of a god; for immediately the Romans raised a bold and joyous shout, and the Etruscans, panic-stricken, ran out of their camp and dispersed.',
 'The Romans attacked the camp, took prisoners all that were left in it, something less than five thousand, and plundered it.',
 'The dead, when counted, proved to be eleven thousand three hundred of the enemy, and of the Romans the same number save one.',
 'This battle is said to have been fought on the Calends of March.',
 'Valerius triumphed after it in a four-horse chariot, being the first consul that ever did so.',
 'And it was a magnificent sight, and did not, as some say, offend the spectators; for, if so, the habit of doing it would not have been so carefully kept up for so many years.',
 'The people were also pleased with the honours which Valerius paid to his colleague in arranging a splendid funeral for him; he also pronounced a funeral oration over him, which was so much approved of by the Romans that from that day forth it became the custom for all good and great men at their deaths to have an oration made over them by the leading men of the time.',
 'This is said to have been older even than the Greek funeral orations, unless, as Anaximenes tells us, Solon introduced this custom.',
 ' X. But the people were vexed and angry, because though Brutus, whom they thought the author of their liberty, would not be consul alone, but had one colleague after another, yet "Valerius," they said, "has got all power into his own hands, and is not so much the heir of the consulship of Brutus as of the tyranny of Tarquin.',
 'And what use is it for him to praise Brutus while he imitates Tarquin in his deeds, swaggering down into the Forum with all the rods and axes before him, from a house larger than the king\'s palace used to be."',
 'Indeed, Valerius lived in rather too splendid a house on the Velian Hill, looking down into the Forum, and difficult to climb up to, so that when he walked down from it he did indeed look like a tragedy king leaving his palace.',
 'But now he proved how valuable a thing it is for a statesman engaged in important matters to keep his ears open to the truth, and shut against flattery.',
 'Hearing from his friends what the people thought of him, he did not argue or grieve at it, but suddenly assembled a number of workmen and during the night destroyed his entire house down to the very foundations, so that on the next day the Romans collected in crowds to see it, admiring the magnanimity of the man, but sorrowing at the destruction of so great and noble a house, which, like many a man, had been put to death undeservedly, and expressing their concern for their consul, who had no house to live in.',
 'Valerius, indeed, had to be entertained by his friends, until the people gave him a site and built him a house upon it, of more moderate proportions than the other, in the place where at the present day stands the temple of Vica Pota.',
 'Wishing to make not only himself but his office cease to be an object of terror to his countrymen, he removed the axes from the bundles of rods carried by the lictors, and when he entered the assembly of the people he ordered his _fasces_ to be bowed and lowered before them, to show respect to the majesty of the people.',
 'This custom the consuls observe to this day.',
 'By these acts he did not really humble himself as he appeared to the Romans to be doing, but he so completely destroyed any illwill which had been felt against him that by giving up the semblance of power he really gained the reality, as the people were eager to serve him and obey him.',

In [ ]:
import numpy as np

In [ ]:
#https://saturncloud.io/blog/how-to-write-large-pandas-dataframes-to-csv-file-in-chunks/
chunk_size = 50000
num_chunks = len(exploded_df ) // chunk_size + 1

for i, chunk in enumerate(np.array_split(exploded_df, num_chunks)):
    chunk.to_csv(f"/content/drive/MyDrive/DaD_2026/Processed_Data/chunked_histents/output_chunk_{i}.csv", index=False)

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [ ]:
exploded_df_sent_text = lives.explode("sent_full_text")

In [ ]:
ents = []
for s in df_exploded['Sents'].values:
   sentences = split_into_sentences(s)
   for sent_text in sentences:
        sentence = Sentence(sent_text)
        tagger.predict(sentence)

        for span in sentence.get_spans("ner"):
            ents.append({
                "entity_text": span.text,
                "label": span.tag,
                "score": float(span.score),
                "sentence": sentence.text
            })

In [ ]:
entities

[{'entity_text': 'Lykurgus',
  'label': 'pers',
  'score': 0.9996962547302246,
  'sent': 'When I had written the lives of Lykurgus the lawgiver and Numa the king, it appeared to me natural to go back to Romulus also, as I was engaged on the history of times so close to his.'},
 {'entity_text': 'Numa',
  'label': 'pers',
  'score': 0.9996939897537231,
  'sent': 'When I had written the lives of Lykurgus the lawgiver and Numa the king, it appeared to me natural to go back to Romulus also, as I was engaged on the history of times so close to his.'},
 {'entity_text': 'Romulus',
  'label': 'pers',
  'score': 0.9996976852416992,
  'sent': 'When I had written the lives of Lykurgus the lawgiver and Numa the king, it appeared to me natural to go back to Romulus also, as I was engaged on the history of times so close to his.'}]

In [ ]:
df = pd.DataFrame.from_dict(ents)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
hi = pd.read_csv("/content/drive/MyDrive/DaD_2026/code_files/Week_2/bert_ner.csv")

In [ ]:
hi

,Unnamed: 0,Title,sent_lim,entity_text,label,score
0,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Senecio, ...",Sossius Senecio,pers,0.924037
1,1,LIFE OF THESEUS.,"I. As in books on geography, Sossius Senecio, ...",Scythia,loc,0.997144
2,2,LIFE OF THESEUS.,"I. As in books on geography, Sossius Senecio, ...",Parallel Lives,pers,0.875612
3,3,LIFE OF THESEUS.,When I had written the lives of Lykurgus the l...,Lykurgus,pers,0.999696
4,4,LIFE OF THESEUS.,When I had written the lives of Lykurgus the l...,Numa,pers,0.999694
...,...,...,...,...,...,...
416464,416464,LIFE OF OTHO.,This website includes information about Projec...,Project,work,0.714812
416465,416465,LIFE OF OTHO.,This website includes information about Projec...,Gutenberg,pers,0.997368
416466,416466,LIFE OF OTHO.,This website includes information about Projec...,Project,work,0.567804
416467,416467,LIFE OF OTHO.,This website includes information about Projec...,Gutenberg,pers,0.995120
416468,416468,LIFE OF OTHO.,This website includes information about Projec...,Foundation,work,0.985375

In [ ]:
 counts = hi[['entity_text','label',"Title"]].value_counts()

In [ ]:
by_book = hi.groupby('Title')[['entity_text',"sent_lim","label"]].value_counts()

In [ ]:
by_book.reset_index().to_csv("/content/drive/MyDrive/DaD_2026/Processed_Data/ner_by_book.csv")

In [ ]:
by_corpus =  hi.groupby("sent_lim")[["Title","entity_text","label"]].value_counts()

In [ ]:
by_corpus.reset_index().to_csv("/content/drive/MyDrive/DaD_2026/Processed_Data/ner_by_sent.csv")

In [ ]:
by_corpus = pd.read_csv("/content/drive/MyDrive/DaD_2026/Processed_Data/ner_by_sent.csv")

In [ ]:
by_corpus

,Unnamed: 0,sent_lim,Title,entity_text,label,count
0,0,"""--""For an instant,"" says Colonel Chesney afte...",LIFE OF CRASSUS.,Chesney,pers,1
1,1,"""--""For an instant,"" says Colonel Chesney afte...",LIFE OF CRASSUS.,Tigris,pers,1
2,2,"""--Arnold's 'History of Rome,' vol.",LIFE OF PYRRHUS.,Arnold,pers,1
3,3,"""--Arnold's 'History of Rome,' vol.",LIFE OF PYRRHUS.,History,work,1
4,4,"""--Arnold's 'History of Rome,' vol.",LIFE OF PYRRHUS.,Rome,loc,1
...,...,...,...,...,...,...
65538,65538,• You provide a full refund of any money paid ...,LIFE OF OTHO.,Gutenberg,pers,4
65539,65539,"• You provide, in accordance with paragraph 1....",COMPARISON OF KIMON AND LUCULLUS.,1.F.3,scope,4
65540,65540,"• You provide, in accordance with paragraph 1....",COMPARISON OF PAULUS AEMILIUS AND TIMOLEON.,1.F.3,scope,4
65541,65541,"• You provide, in accordance with paragraph 1....",LIFE OF CATO.,1.F.3,scope,4
65542,65542,"• You provide, in accordance with paragraph 1....",LIFE OF OTHO.,1.F.3,scope,4

In [ ]:
by_corpus.iloc[0]['entity_text']

'Chesney'

In [ ]:
by_corpus.iloc[0]['sent_lim']

'"--"For an instant," says Colonel Chesney after getting to land, "I saw the keel of the Tigris uppermost (near the stern); she went down bow foremost, and having struck the bottom in that position, she probably turned round on the bow as a pivot, and thus showed part of her keel for an instant at the other extremity; but her paddle beams, floats, and parts of the sides were already broken up, and actually floated ashore, so speedy and terrific had been the work of destruction." ('

In [ ]:
by_corpus

entity_text  sent_lim                                                                                                                                                                                                                                                                                                                                                                                                                  label
&            Drumann has attempted it (_Geschichte Roms_, Pompeii, p. 451, &c.)]  [Footnote 276: Plutarch means the fort which he has mentioned in the preceding chapter without there giving it a name; the Symphorium of Dion.                                                                                                                                                                                                       scope    1
             This king, who is called Abriorix, is named Ambiorix by Cæsar (_Gallic War_, 24, &c.) The Gauls, after an unsuccessful attempt on the camp, persuaded the Romans to leave it under a promise that they should have a safe passage through the country of the Eburones.                                                                                                                                                    scope    1
&c           As to the affair of Catiline, see the Lives of Cæsar and Cato, and the notes; and Drumann, _Tullii_, p. 385, &c.  [170] See the Life of Sulla, c. 32.                                                                                                                                                                                                                                                                     scope    1
&c.          The present condition of the town is described by Hamilton (_Researches_, i. 306, &c.): "The population and prosperity of Sinope are not such as might be expected in a place affording such a safe harbour between Constantinople and Trebizond.                                                                                                                                                                         scope    1
             [510] This was C. Cassius Longinus, who accompanied Crassus in his Parthian campaign (Life of Crassus, c. 18, &c.).                                                                                                                                                                                                                                                                                                       scope    1
                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
Ætolians     He announced to the rest of the citizens that the land should be divided among them, that they should be relieved from all their debts, and that all resident aliens should be submitted to an examination, in order that the best of them might be selected to become full citizens of Sparta, and help to defend the city from falling a prey to Ætolians and Illyrians for want of men to defend her.                  pers     1
             Ætolia and Ætolians, ii.                                                                                                                                                                                                                                                                                                                                                                                                  pers     1
ædiles       It happened that at the election of ædiles some men came to blows and no small number were killed near Pompeius, and as his garments were drenched with blood, he changed them.                                                                                                                                                                                                                                           pers     1
êcheiois     [Footnote 71: Plutarch seems to mean something like drums furnished with bells or rattles; but his description is not very clear, and the passage may be rendered somewhat differently from what I have rendered it: "but they have instruments to beat upon ([Greek: rhoptra] ῥόπτρα), made of skin, and hollow, which they stretch round brass sounders" ([Greek: êcheiois] ἠχείοις, whatever the word may mean here).  pers     1
Œneadæ       This cruelty made many of the friends of Alexander fear him, and especially Antipater,[417] who now formed a secret league with the Ætolians, who also feared Alexander because when he heard of the destruction of the people of Œneadæ, he said that he himself, and not the sons of the people of Œneadæ, would be revenged upon the Ætolians.                                                                         loc      2
Name: count, Length: 65026, dtype: int64

In [ ]:
 hi[['entity_text','label']].value_counts().to_csv("/content/drive/MyDrive/DaD_2026/Processed_Data/ner_across_corpus.csv")

In [ ]:
df

,Unnamed: 0,Title,Text,Sents
0,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","I. As in books on geography, Sossius Senecio, ..."
1,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","nd fabulous, inhabited by poets and mythologer..."
2,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...",When I had written the lives of Lykurgus the l...
3,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","So when I was reflecting, in the words of Aesc..."
4,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","Whom shall I match in fight, what trusty friend?"""
...,...,...,...,...
95,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...",He then called a public meeting and made These...
96,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...",It is said that when the cup was overset the p...
97,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...",XIII.
98,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","But the sons of Pallas, who had previously to ..."
99,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...",They consequently declared war.

In [ ]:
    reader = pd.read_csv(input_filename, chunksize=chunksize, iterator=True)

'I. As in books on geography, Sossius Senecio, the writers crowd the countries of which they know nothing into the furthest margins of their maps, and write upon them legends such as, "In this direction lie waterless deserts full of wild beasts;" or, "Unexplored morasses;" or, "Here it is as cold as Scythia;" or, "A frozen sea;" so I, in my writings on Parallel Lives, go through that period of time where history rests on the firm basis of facts, and may truly say, "All beyond this is portentous a'

In [ ]:
df["Text"][0]

'   I. As in books on geography, Sossius Senecio, the writers crowd the countries of which they know nothing into the furthest margins of their maps, and write upon them legends such as, "In this direction lie waterless deserts full of wild beasts;" or, "Unexplored morasses;" or, "Here it is as cold as Scythia;" or, "A frozen sea;" so I, in my writings on Parallel Lives, go through that period of time where history rests on the firm basis of facts, and may truly say, "All beyond this is portentous and fabulous, inhabited by poets and mythologers, and there is nothing true or certain."  When I had written the lives of Lykurgus the lawgiver and Numa the king, it appeared to me natural to go back to Romulus also, as I was engaged on the history of times so close to his. So when I was reflecting, in the words of Aeschylus,      "Against this chieftain, who can best contend?     Whom shall I match in fight, what trusty friend?"  it occurred to me to compare the founder of the fair and famous city of Athens with him, and to contrast Theseus with the father of unconquered glorious Rome. Putting aside, then, the mythological element, let us examine his story, and wherever it obstinately defies probability, and cannot be explained by natural agency, let us beg the indulgence of our readers, who will kindly make allowance for tales of antiquity.  II. Theseus appears to have several points of resemblance to Romulus. Both were unacknowledged illegitimate children, and were reputed to descend from the Gods.      "Both warriors, well we all do know,"  and both were wise as well as powerful. The one founded Rome, while the other was the joint founder of Athens; and these are two of the most famous of cities. Both carried off women by violence, and neither of them escaped domestic misfortune and retribution, but towards the end of their lives both were at variance with their countrymen, if we may put any trust in the least extravagant writings upon the subject.  III. Theseus traced his descent on the father\'s side from Erechtheus and the original Autochthones,[A] while on the mother\'s side he was descended from Pelops. For Pelops surpassed all the other princes of the Peloponnesus in the number of his children as well as in wealth; and of these he gave many of his daughters in marriage to the chief men of the country, and established many of his sons as rulers in various cities. One of these, Pittheus, the grandfather of Theseus, founded Troezen, which is indeed but a little state, though he had a greater reputation than any man of his time for eloquence and wisdom. The nature of this wisdom of his seems to have been much of the same kind as that which made the reputation of Hesiod, in the collection of maxims known as the \'Works and Days.\' One of these maxims is indeed ascribed to Pittheus:       "Let promised pay be truly paid to friends."  At any rate, this is what Aristotle the philosopher has recorded; and also Euripides, when he speaks of Hippolytus as "child of holy Pittheus," shows the prevailing opinion about Pittheus. Now Aegeus desired to have children, and the Oracle at Delphi is said to have given him the well-known response, forbidding him to have intercourse with any woman before he reached Athens, but not appearing to explain this clearly. Consequently, on his way home, he went to Troezen, and asked the advice of Pittheus about the response of the God, which ran thus:      "Great chief, the wine-skin\'s foot must closed remain,     Till thou to Athens art returned again."  Pittheus clearly perceived what the oracle must mean, and persuaded or cheated Aegeus into an intrigue with Aethra. Afterwards, when he discovered that he had conversed with the daughter of Pittheus, as he imagined that she might prove with child, he left behind him his sword and sandals hidden under a great stone, which had a hollow inside it exactly fitting them. This he told to Aethra alone, and charged her if a son of his should be born, and on growing to man\'s estate should be able to lift the stone and take from under it the deposit, that she should send him at once with these things to himself, in all secrecy, and as far as possible concealing his journey from observation. For he greatly feared the sons of Pallas, who plotted against him, and despised him on account of his childlessness, they themselves being fifty brothers, all the sons of Pallas.  [Footnote A: Autochthones was the name by which the original citizens of Athens called themselves, meaning that they were sprung from the soil itself, not immigrants from some other country.]  IV. When Aethra\'s child was born, some writers say that he was at once named Theseus, from the tokens placed under the stone; others say that he was afterwards so named at Athens, when Aegeus acknowledged him as his son. He was brought up by his grandfather Pittheus, and had a master and tutor, Konnidas, to whom even to the present day, the Athenians sacrifice a ram on the day before the feast of Theseus, a mark of respect which is much more justly due to him, than those which they pay to Silanion and Parrhasius, who have only made pictures and statues of Theseus.  V. As it was at that period still the custom for those who were coming to man\'s estate to go to Delphi and offer to the god the first-fruits of their hair (which was then cut for the first time),[A] Theseus went to Delphi, and they say that a place there is even to this day named after him. But he only cut the front part of his hair, as Homer tells us the Abantes did, and this fashion of cutting the hair was called Theseus\'s fashion because of him. The Abantes first began to cut their hair in this manner, not having, as some say, been taught to do so by the Arabians, nor yet from any wish to imitate the Mysians, but because they were a warlike race, and met their foes in close combat, and studied above all to come to a hand-to-hand fight with their enemy, as Archilochus bears witness in his verses:      "They use no slings nor bows,       Euboea\'s martial lords,     But hand to hand they close       And conquer with their swords."  So they cut their hair short in front, that their enemies might not grasp it. And they say that Alexander of Macedon for the same reason ordered his generals to have the beards of the Macedonians shaved, because they were a convenient handle for the enemy to grasp.  [Footnote A: The first cutting of the hair was always an occasion of solemnity among the Greeks, the hair being dedicated to some god. The first instance of this is in Homer\'s Iliad, where Achilles speaks of having dedicated his hair to the river Spercheius. The Athenian youth offered their hair to Herakles. The Roman emperor Nero, in later times, imitated this custom.]  VI. Now while he was yet a child, Aethra concealed the real parentage of Theseus, and a story was circulated by Pittheus that his father was Poseidon. For the people of Troezen have an especial reverence for Poseidon; he is their tutelar deity; to him they offer first-fruits of their harvest, and they stamp their money with the trident as their badge. But when he was grown into a youth, and proved both strong in body and of good sound sense, then Aethra led him to the stone, told him the truth about his father, and bade him take the tokens from beneath it and sail to Athens with them. He easily lifted the stone, but determined not to go to Athens by sea, though the voyage was a safe and easy one, and though his mother and his grandfather implored him to go that way. By land it was a difficult matter to reach Athens, as the whole way was infested with robbers and bandits. That time, it seems, produced men of great and unwearied strength and swiftness, who made no good use of these powers, but treated all men with overbearing insolence, taking advantage of their strength to overpower and slay all who fell into their hands, and disregarding justice and right and kindly feeling, which they said were only approved of by those who dared not do injury to others, or feared to be injured themselves, while men who could get the upper hand by force might disregard them. Of these ruffians, Herakles in his wanderings cut off a good many, but others had escaped him by concealing themselves, or had been contemptuously spared by him on account of their insignificance. But Herakles had the misfortune to kill Iphitus, and thereupon sailed to Lydia and was for a long time a slave in that country under Omphale, which condition he had imposed upon himself as a penance for the murder of his friend. During this period the country of Lydia enjoyed peace and repose; but in Greece the old plague of brigandage broke out afresh, as there was now no one to put it down. So that the journey overland to Athens from Peloponnesus was full of peril; and Pittheus, by relating to Theseus who each of these evildoers was, and how they treated strangers, tried to prevail upon him to go by sea. But it appears that Theseus had for a long time in his heart been excited by the renown of Herakles for courage: he thought more of him than of any one else, and loved above all to listen to those who talked of him, especially if they had seen and spoken to him. Now he could no longer conceal that he was in the same condition as Themistokles in later times, when he said that the trophy of Miltiades would not let him sleep. Just so did the admiration which Theseus conceived for Herakles make him dream by night of his great exploits, and by day determine to equal them by similar achievements of his own.  VII. As it happened, they were connected, being second cousins; for Aethra was the daughter of Pittheus, and Alkmena the daughter of Lysidike, and Lysidike and Pittheus were brother and sister, being the children of Pelops and Hippodameia. So Theseus thought that it would be a great and unbearable disgrace to him that his cousin should go everywhere and clear the sea and land of the brigands who infested them, and he should refuse to undertake the adventures that came in his way; throwing discredit upon his reputed father by a pusillanimous flight by sea, and upon his real father by bringing him only the sandals and an unfleshed sword, and not proving his noble birth by the evidence of some brave deed accomplished by him. In this spirit he set out on his journey, with the intention of doing wrong to no one, but of avenging himself on any one who offered wrong to him.  VIII. And first in Epidaurus he slew Periphetes, who used a club as his weapon, and on this account was called the club-bearer, because he laid hands upon him and forbade him to proceed farther on his way. The club took his fancy, and he adopted it as a weapon, and always used it, just as Herakles used his lion\'s skin; for the skin was a proof of how huge a beast the wearer had overcome, while the club, invincible in the hands of Theseus, had yet been worsted when used against him. At the Isthmus he destroyed Sinis the Pine-bender by the very device by which he had slain so many people, and that too without having ever practised the art, proving that true valour is better than practice and training. Sinis had a daughter, a tall and beautiful girl, named Perigoune. When her father fell she ran and hid herself. Theseus sought her everywhere, but she fled into a place where wild asparagus grew thick, and with a simple child-like faith besought the plants to conceal her, as if they could understand her words, promising that if they did so she never would destroy or burn them. However, when Theseus called to her, pledging himself to take care of her and do her no hurt, she came out, and afterwards bore Theseus a son, named Melanippus. She afterwards was given by Theseus in marriage to Deïoneus, the son of Eurytus of Oechalia. Ioxus, a son of Melanippus, and Theseus\'s grandchild, took part in Ornytus\'s settlement in Caria; and for this reason the descendants of Ioxus have a family custom not to burn the asparagus plant, but to reverence and worship it.  IX. Now the wild sow of Krommyon, whom they called Phaia, was no ordinary beast, but a fierce creature and hard to conquer. This animal he turned out of his way to destroy, that it might not be thought that he performed his exploits of necessity. Besides, he said, a brave man need only punish wicked men when they came in his way, but that in the case of wild beasts he must himself seek them out and attack them. Some say that Phaia was a murderous and licentious woman who carried on brigandage at Krommyon, and was called a sow from her life and habits, and that Theseus put her to death.  X. Before coming to Megara he slew Skeiron by flinging him down a precipice into the sea, so the story runs, because he was a robber, but some say that from arrogance he used to hold out his feet to strangers and bid them wash them, and that then he kicked the washers into the sea. But Megarian writers, in opposition to common tradition, and, as Simonides says, "warring with all antiquity," say that Skeiron was not an arrogant brigand, but repressed brigandage, loved those who were good and just, and was related to them. For, they point out, Aeakus is thought to have been the most righteous of all the Greeks, and Kychreus of Salamis was worshipped as a god, and the virtue of Peleus and Telamon is known to all. Yet Skeiron was the son-in-law of Kychreus, and father-in-law of Aeakus, and grandfather of Peleus and Telamon, who were both of them sons of Endeis, the daughter of Skeiron and his wife Chariklo. It is not then reasonable to suppose that these, the noblest men of their time, would make alliances with a malefactor, and give and receive from him what they prized most dearly. But they say that Theseus slew Skeiron, not when he first went to Athens, but that afterwards he took the town of Eleusis which belonged to the Megarians, by dealing treacherously with Diokles, who was the chief magistrate there, and that on that occasion he killed Skeiron. This is what tradition says on both sides.  XI. At Eleusis Theseus overcame Kerkyon of Arcadia in wrestling and killed him, and after journeying a little farther he killed Damastes, who was surnamed Prokroustes, by compelling him to fit his own body to his bed, just as he used to fit the bodies of strangers to it. This he did in imitation of Herakles; for he used to retort upon his aggressors the same treatment which they intended for him. Thus Herakles offered up Busiris as a sacrifice, and overcame Antaeus in wrestling, and Kyknus in single combat, and killed Termerus by breaking his skull. This is, they say, the origin of the proverb, "A Termerian mischief," for Termerus, it seems, struck passers-by with his head, and so killed them. So also did Theseus sally forth and chastise evildoers, making them undergo the same cruelties which they practised on others, thus justly punishing them for their crimes in their own wicked fashion.  XII. As he proceeded on his way, and reached the river Kephisus, men of the Phytalid race were the first to meet and greet him. He demanded to be purified from the guilt of bloodshed, and they purified him, made propitiatory offerings, and also entertained him in their houses, being the first persons from whom he had received any kindness on his journey. It is said to have been on the eighth day of the month Kronion, which is now called Hekatombeion, that he came to his own city. On entering it he found public affairs disturbed by factions, and the house of Aegeus in great disorder; for Medea, who had been banished from Corinth, was living with Aegeus, and had engaged by her drugs to enable Aegeus to have children. She was the first to discover who Theseus was, while Aegeus, who was an old man, and feared every one because of the disturbed state of society, did not recognise him. Consequently she advised Aegeus to invite him to a feast, that she might poison him. Theseus accordingly came to Aegeus\'s table. He did not wish to be the first to tell his name, but, to give his father an opportunity of recognising him, he drew his sword, as if he meant to cut some of the meat with it, and showed it to Aegeus. Aegeus at once recognised it, overset the cup of poison, looked closely at his son and embraced him. He then called a public meeting and made Theseus known as his son to the citizens, with whom he was already very popular because of his bravery. It is said that when the cup was overset the poison was spilt in the place where now there is the enclosure in the Delphinium, for there Aegeus dwelt; and the Hermes to the east of the temple there they call the one who is "at the door of Aegeus."  XIII. But the sons of Pallas, who had previously to this expected that they would inherit the kingdom on the death of Aegeus without issue, now that Theseus was declared the heir, were much enraged, first that Aegeus should be king, a man who was merely an adopted child of Pandion, and had no blood relationship to Erechtheus, and next that Theseus, a stranger and a foreigner, should inherit the kingdom. They consequently declared war. Dividing themselves into two bodies, the one proceeded to march openly upon the city from Sphettus, under the command of Pallas their father, while the other lay in ambush at Gargettus, in order that they might fall upon their opponents on two sides at once. But there was a herald among them named Leos, of the township of Agnus, who betrayed the plans of the sons of Pallas to Theseus. He suddenly attacked those who were in ambush, and killed them all, hearing which the other body under Pallas dispersed. From this time forth they say that the township of Pallene has never intermarried with that of Agnus, and that it is not customary amongst them for heralds to begin a proclamation with the words "Acouete Leo," (Oyez) for they hate the name of Leo[A] because of the treachery of that man.  [Footnote A: The Greek word _leos_ signifies people.]  XIV. Now Theseus, who wished for employment and also to make himself popular with the people, went to attack the bull of Marathon, who had caused no little trouble to the inhabitants of Tetrapolis. He overcame the beast, and drove it alive through the city for all men to see, and then sacrificed it to Apollo of Delphi. Hekale, too, and the legend of her having entertained Theseus, does not seem altogether without foundation in fact; for the people of the neighbouring townships used to assemble and perform what was called the Hekalesian sacrifice to Zeus Hekalus, and they also used to honour Hekale, calling her by the affectionate diminutive Hekaline, because she also, when feasting Theseus, who was very young, embraced him in a motherly way, and used such like endearing diminutives. She also made a vow on Theseus\'s behalf, when he was going forth to battle, that if he returned safe she would sacrifice to Zeus; but as she died before he returned, she had the above-mentioned honours instituted by command of Theseus, as a grateful return for her hospitality. This is the legend as told by Philochorus.  XV. Shortly after this the ship from Crete arrived for the third time to collect the customary tribute. Most writers agree that the origin of this was, that on the death of Androgeus, in Attica, which was ascribed to treachery, his father Minos went to war, and wrought much evil to the country, which at the same time was afflicted by scourges from Heaven (for the land did not bear fruit, and there was a great pestilence and the rivers sank into the earth). So that as the oracle told the Athenians that, if they propitiated Minos and came to terms with him, the anger of Heaven would cease and they should have a respite from their sufferings, they sent an embassy to Minos and prevailed on him to make peace, on the condition that every nine years they should send him a tribute of seven youths and seven maidens. The most tragic of the legends states these poor children when they reached Crete were thrown into the Labyri

In [ ]:
df_exploded.to_csv("/content/drive/MyDrive/sents_ml.csv")

In [ ]:
df.to_csv("/content/drive/MyDrive/historical_NER.csv")

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/sents_ml.csv', nrows=1000)

In [ ]:
df

,Unnamed: 0,Title,Text,Sents
0,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","I. As in books on geography, Sossius Senecio, ..."
1,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","nd fabulous, inhabited by poets and mythologer..."
2,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...",When I had written the lives of Lykurgus the l...
3,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","So when I was reflecting, in the words of Aesc..."
4,0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Seneci...","Whom shall I match in fight, what trusty friend?"""
...,...,...,...,...
995,3,LIFE OF LYKURGUS.,I. With regard to Lykurgus the lawgiver the...,This is what is said about their marriage cere...
996,3,LIFE OF LYKURGUS.,I. With regard to Lykurgus the lawgiver the...,XV.
997,3,LIFE OF LYKURGUS.,I. With regard to Lykurgus the lawgiver the...,A father had not the right of bringing up his ...
998,3,LIFE OF LYKURGUS.,I. With regard to Lykurgus the lawgiver the...,"If they thought it well-built and strong, they..."
999,3,LIFE OF LYKURGUS.,I. With regard to Lykurgus the lawgiver the...,Wherefore the women used to wash their newborn...

In [ ]:
df.iloc[680]['Text']

'   Historians are not agreed upon the origin and meaning of the famous name of Rome, which is so celebrated through all the world. Some relate that the Pelasgi, after wandering over the greater part of the world, and conquering most nations, settled there, and gave the city its name from their own strength in battle.[A] Others tell us that after the capture of Troy some fugitives obtained ships, were carried by the winds to the Tyrrhenian or Tuscan coast, and cast anchor in the Tiber. There the women, who had suffered much from the sea voyage, were advised by one who was accounted chief among them for wisdom and noble birth, Roma by name, to burn the ships. At first the men were angry at this, but afterwards, being compelled to settle round about the Palatine Hill, they fared better than they expected, as they found the country fertile and the neighbours hospitable; so they paid great honour to Roma, and called the city after her name. From this circumstance, they say, arose the present habit of women kissing their male relatives and connections; because those women, after they had burned the ships, thus embraced and caressed the men, trying to pacify their rage.  [Footnote A: The Greek [Greek: rhômê] = strength.]  II. Some say that Roma, who gave the name to the city, was the daughter of Italus and Leucaria, or of Telephus the son of Hercules, and the wife of Aeneas, while others say that she was the daughter of Ascanius the son of Aeneas. Others relate that Romanus, the son of Odysseus and Circe, founded the city, or that it was Romus, the son of Hemathion, who was sent from Troy by Diomedes; or Romis the despot of the Latins, who drove out of his kingdom the Tyrrhenians, who, starting from Thessaly, had made their way to Lydia, and thence to Italy. And even those who follow the most reasonable of these legends, and admit that it was Romulus who founded the city after his own name, do not agree about his birth; for some say that he was the son of Aeneas and Dexithea the daughter of Phorbas, and with his brother Romus was brought to Italy when a child, and that as the river was in flood, all the other boats were swamped, but that in which the children were was carried to a soft bank and miraculously preserved, from which the name of Rome was given to the place. Others say that Roma, the daughter of that Trojan lady, married Latinus the son of Telemachus and bore a son, Romulus; while others say that his mother was Aemilia the daughter of Aeneas and Lavinia, by an intrigue with Mars; while others give a completely legendary account of his birth, as follows:  In the house of Tarchetius, the king of the Albani, a cruel and lawless man, a miracle took place. A male figure arose from the hearth, and remained there for many days. Now there was in Etruria an oracle of Tethys, which told Tarchetius that a virgin must be offered to the figure; for there should be born of her a son surpassing all mankind in strength, valour, and good fortune. Tarchetius hereupon explained the oracle to one of his daughters, and ordered her to give herself up to the figure; but she, not liking to do so, sent her servant-maid instead. Tarchetius, when he learned this, was greatly incensed, and cast them both into prison, meaning to put them to death. However, in a dream, Vesta appeared to him, forbidding him to slay them. In consequence of this he locked them up with a loom, telling them that when they had woven the piece of work upon it they should be married. So they wove all day, and during the night other maidens sent by Tarchetius undid their work again. Now when the servant-maid was delivered of twins, Tarchetius gave them to one Teratius, and bade him destroy them. He laid them down near the river; and there they were suckled by a she-wolf, while all sorts of birds brought them morsels of food, until one day a cowherd saw them. Filled with wonder he ventured to come up to the children and bear them off. Saved from death in this manner they grew up, and then attacked and slew Tarchetius. This is the legend given by one Promathion, the compiler of a history of Italy.  III. But the most credible story, and that has most vouchers for its truth, is that which was first published in Greece by Diokles of Peparethos, a writer whom Fabius Pictor has followed in most points. There are variations in this legend also; but, generally speaking, it runs as follows:  The dynasty established by Aeneas at Alba Longa, came down to two brothers, Numitor and Amulius. Amulius offered his brother the choice between the sovereign power and the royal treasure, including the gold brought from Troy. Numitor chose the sovereign power. But Amulius, possessing all the treasure, and thereby having more power than his brother, easily dethroned him, and, as he feared his brother\'s daughter might have children who would avenge him, he made her a priestess of Vesta, sworn to celibacy for ever. This lady is named by some Ilia, by others Rhea or Silvia. After no long time she was found to be with child, against the law of the Vestals. Her life was saved by the entreaties of Antho, the king\'s daughter, but she was closely imprisoned, that she might not be delivered without Amulius\'s knowledge. She bore two children of remarkable beauty and size, and Amulius, all the more alarmed at this, bade an attendant take them and expose them. Some say that this man\'s name was Faustulus, while others say that this was not his name, but that of their rescuer. However, he placed the infants in a cradle, and went down to the river with the intention of throwing them into it, but seeing it running strong and turbulently, he feared to approach it, laid down the cradle near the bank and went away. The river, which was in flood, rose, and gently floated off the cradle, and carried it down to a soft place which is now called Cermalus, but anciently, it seems, was called Germanus, because brothers are called germani.  IV. Near this place was a fig-tree, which they called Ruminalius, either from Romulus, as most persons imagine, or because cattle came to ruminate in its shade, or, more probably, because of the suckling of the children there, for the ancients called the nipple _rouma_. Moreover, they call the goddess who appears to have watched over the children Roumilia, and to her they sacrifice offerings without wine, and pour milk as a libation upon her altar.  It is said that while the infants were lying in this place, the she-wolf suckled them, and that a woodpecker came and helped to feed and watch over them. Now these animals are sacred to the god Mars; and the Latins have a peculiar reverence and worship for the woodpecker. These circumstances, therefore, did not a little to confirm the tale of the mother of the children, that their father was Mars, though some say that she was deceived by Amulius himself, who, after condemning her to a life of virginity, appeared before her dressed in armour, and ravished her. Others say that the twofold meaning of the name of their nurse gave rise to this legend, for the Latins use the word _lupa_ for she-wolves, and also for unchaste women, as was the wife of Faustulus, who brought up the children, Acca Laurentia by name. To her also the Romans offer sacrifice, and in the month of April the priest of Mars brings libations to her, and the feast is called Laurentia.  V. The Romans also worship another Laurentia, for this reason: The priest of Hercules, weary with idleness, proposed to the god to cast the dice on the condition that, if he won, he should receive something good from the god, while if he lost, he undertook to provide the god with a bountiful feast and a fair woman to take his pleasure with. Upon these conditions he cast the dice, first for the god, and then for himself, and was beaten. Wishing to settle his wager properly, and making a point of keeping his word, he prepared a feast for the god, and hired Laurentia, then in the pride of her beauty, though not yet famous. He feasted her in the temple, where he had prepared a couch, and after supper he locked her in, that the god might possess her. And, indeed, the god is said to have appeared to the lady, and to have bidden her go early in the morning into the market-place, and to embrace the first man she met, and make him her friend. There met her a citizen far advanced in years, possessing a fair income, childless, and unmarried. His name was Tarrutius. He took Laurentia to himself, and loved her, and upon his death left her heiress to a large and valuable property, the greater part of which she left by will to the city. It is related of her, that after she had become famous, and was thought to enjoy the favour of Heaven, she vanished near the very same spot where the other Laurentia lay buried. This place is now called Velabrum, because during the frequent overflowings of the river, people used there to be ferried over to the market-place; now they call ferrying _velatura_. Some say that the road from the market-place to the circus, starting from this point, used to be covered with sails or awnings by those who treated the people to a spectacle; and in the Latin tongue a sail is called _velum_. This is why the second Laurentia is honoured by the Romans.  VI. Now Faustulus, the swineherd of Amulius, kept the children concealed from every one, though some say that Numitor knew of it, and shared the expense of their education. They were sent to Gabii to learn their letters, and everything else that well-born children should know; and they were called Romulus and Remus, because they were first seen sucking the wolf. Their noble birth showed itself while they were yet children, in their size and beauty; and when they grew up they were manly and high-spirited, of invincible courage and daring. Romulus, however, was thought the wiser and more politic of the two, and in his discussions with the neighbours about pasture and hunting, gave them opportunities of noting that his disposition was one which led him to command rather than to obey. On account of these qualities they were beloved by their equals and the poor, but they despised the king\'s officers and bailiffs as being no braver than themselves, and cared neither for their anger nor their threats. They led the lives and followed the pursuits of nobly born men, not valuing sloth and idleness, but exercise and hunting, defending the land against brigands, capturing plunderers, and avenging those who had suffered wrong. And thus they became famous.  VII. Now a quarrel arose between the herdsmen of Numitor and those of Amulius, and cattle were driven off by the former. Amulius\'s men, enraged at this, fought and routed the others, and recovered a great part of the booty. They cared nothing for Numitor\'s anger, but collected together many needy persons and slaves, and filled them with a rebellious spirit. While Romulus was absent at a sacrifice (for he was much addicted to sacrifices and divination), the herdsmen of Numitor fell in with Remus, accompanied by a small band, and fought with him. After many wounds had been received on both sides, Numitor\'s men conquered and took Remus alive. Remus was brought before Numitor, who did not punish him, as he feared his brother\'s temper, but went to his brother and begged for justice, saying that he had suffered wrong at the hands of the king his brother\'s servants. As all the people of Alba sympathised with Remus, and feared that he would be unjustly put to death, or worse, Amulius, alarmed at them, handed over Remus to his brother Numitor, to deal with as he pleased. Numitor took him, and as soon as he reached home, after admiring the bodily strength and stature of the youth, which surpassed all the rest, perceiving in his looks his courageous and fiery spirit, undismayed by his present circumstances, and having heard that his deeds corresponded to his appearance, and above all, as seems probable, some god being with him and watching over the first beginnings of great events, he was struck by the idea of asking him to tell the truth as to who he was, and how he was born, giving him confidence and encouragement by his kindly voice and looks. The young man boldly said, "I will conceal nothing from you, for you seem more like a king than Amulius. You hear and judge before you punish, but he gives men up to be punished without a trial. Formerly we (for we are twins) understood that we were the sons of Faustulus and Laurentia, the king\'s servants; but now that we are brought before you as culprits, and are falsely accused and in danger of our lives, we have heard great things about ourselves. Whether they be true or not, we must now put to the test. Our birth is said to be a secret, and our nursing and bringing up is yet stranger, for we were cast out to the beasts and the birds, and were fed by them, suckled by a she-wolf, and fed with morsels of food by a woodpecker as we lay in our cradle beside the great river. Our cradle still exists, carefully preserved, bound with brazen bands, on which is an indistinct inscription, which hereafter will serve as a means by which we may be recognised by our parents, but to no purpose if we are dead." Numitor, considering the young man\'s story, and reckoning up the time from his apparent age, willingly embraced the hope which was dawning on his mind, and considered how he might obtain a secret interview with his daughter and tell her of all this; for she was still kept a close prisoner.  VIII. Faustulus, when he heard of Remus being captured and delivered up to Numitor, called upon Romulus to help him, and told him plainly all about his birth; although previously he had hinted so much, that any one who paid attention to his words might have known nearly all about it; and he himself with the cradle ran to Numitor full of hopes and fears, now that matters had come to a critical point. He was viewed with suspicion by the guards at the king\'s gate, and while they were treating him contemptuously, and confusing him by questions, they espied the cradle under his cloak. Now it chanced that one of them had been one of those who had taken the children to cast them away, and had been present when they were abandoned. This man, seeing the cradle and recognising it by its make and the inscription on it, suspected the truth, and at once told the king and brought the man in to be examined. Faustulus, in those dire straits, did not altogether remain unshaken, and yet did not quite allow his secret to be wrung from him. He admitted that the boys were alive, but said that they were living far away from Alba, and that he himself was bringing the cradle to Ilia, who had often longed to see and touch it to confirm her belief in the life of her children. Now Amulius did what men generally do when excited by fear or rage. He sent in a great hurry one who was a good man and a friend of Numitor, bidding him ask Numitor whether he had heard anything about the survival of the children. This man on arrival, finding Numitor all but embracing Remus, confirmed his belief that he was his grandson, and bade him take his measures quickly, remaining by him himself to offer assistance. Even had they wished it, there was no time for delay; for Romulus was already near, and no small number of the citizens, through hatred and fear of Amulius, were going out to join him. He himself brought no small force, arrayed in companies of a hundred each. Each of these was led by a man who carried a bundle of sticks and straw upon a pole. The Latins called these _manipla_; and from this these companies are even at the present day called _maniples_ in the Roman army. Now as Remus raised a revolt within, while Romulus assailed the palace without, the despot was captured and put to death without having been able to do anything, or take any measures for his own safety.  The greater part of the above story is told by Fabius Pictor and Diokles of Peparethos, who seem to have been the first historians of the foundation of Rome. The story is doubted by many on account of its theatrical and artificial form, yet we ought not to disbelieve it when we consider what wondrous works are wrought by chance, and when, too, we reflect on the Roman Empire, which, had it not had a divine origin, never could have arrived at its present extent.  IX. After the death of Amulius, and the reorganisation of the kingdom, the twins, who would not live in Alba as subjects, and did not wish to reign there during the life of their grandfather, gave up the sovereign power to him, and, having made a suitable provision for their mother, determined to dwell by themselves, and to found a city in the parts in which they themselves had been reared; at least, this is the most probable of the various reasons which are given. It may also have been necessary, as many slaves and fugitives had gathered round them, either that they should disperse these men and so lose their entire power, or else go and dwell alone amongst them. It is clear, from the rape of the Sabine women, that the citizens of Alba would not admit these outcasts into their own body, since that deed was caused, not by wanton insolence, but by necessity, as they could not obtain wives by fair means; for after carrying the women off they treated them with the greatest respect. Afterwards, when the city was once founded, they made it a sanctuary for people in distress to take refuge in, saying that it belonged to the god Asylus; and they received in it all sorts of persons, not giving up slaves to their masters, debtors to their creditors, or murderers to their judges, but saying that, in accordance with a Pythian oracle, the sanctuary was free to all; so that the city soon became full of men, for they say that at first it contained no less than a thousand hearths. Of this more hereafter. When they were proceeding to found the city, they at once quarrelled about its site. Romulus fixed upon what is now called Roma Quadrata, a square piece of ground, and wished the city to be built in that place; but Remus preferred a strong position on Mount Aventino, which, in memory of him, was called the Remonium, and now is called Rignarium.  They agreed to decide their dispute by watching the flight of birds, and having taken their seats apart, it is said that six vultures appeared to Remus, and afterwards twice as many to Romulus. Some say that Remus really saw his vultures, but that Romulus only pretended to have seen them, and when Remus came to him, then the twelve appeared to Romulus; for which reason the Romans at the present day draw their auguries especially from vultures. Herodorus of Pontus says that Hercules delighted in the sight of a vulture, when about to do any great action. It is the most harmless of all creatures, for it injures neither crops, fruit, nor cattle, and lives entirely upon dead corpses. It does not kill or injure anything that has life, and even abstains from dead birds from its relationship to them. Now eagles, and owls, and falcons, peck and kill other birds, in spite of Aeschylus\'s line,      "Bird-eating bird polluted e\'er must be."  Moreover, the other birds are, so to speak, ever before our eyes, and continually remind us of their presence; but the vulture is seldom seen, and it is difficult to meet with its young, which has suggested to some persons the strange idea that vultures come from some other world to pay us their rare visits, which are like those occurrences which, according to the soothsayers, do not happen naturally or spontaneously, but by the interposition of Heaven.  X. When Remus discovered the deceit he was very angry, and, while Romulus was digging a trench round where the city wall was to be built, he jeered at the works, and hindered them. At last, as he jumped over it, he was struck dead either by Romulus himself, or by Celer, one of his companions. In this fight, Faustulus was slain, and also Pleistinus, who is said to have been Faustul

In [ ]:
sents = pd.read_csv("/content/drive/MyDrive/DaD_2026/sent_lims.csv")

In [ ]:
sents

,Unnamed: 0.1,Unnamed: 0,X,Title,sent_lim
0,0,2,2,LIFE OF THESEUS.,"I. As in books on geography, Sossius Senecio, ..."
1,0,2,2,LIFE OF THESEUS.,"nd fabulous, inhabited by poets and mythologer..."
2,0,2,2,LIFE OF THESEUS.,When I had written the lives of Lykurgus the l...
3,0,2,2,LIFE OF THESEUS.,"So when I was reflecting, in the words of Aesc..."
4,0,2,2,LIFE OF THESEUS.,"Whom shall I match in fight, what trusty friend?"""
...,...,...,...,...,...
46095,67,69,69,LIFE OF OTHO.,Project Gutenberg™ eBooks are often created fr...
46096,67,69,69,LIFE OF OTHO.,"Thus, we do not necessarily keep eBooks in com..."
46097,67,69,69,LIFE OF OTHO.,Most people start at our website which has the...
46098,67,69,69,LIFE OF OTHO.,This website includes information about Projec...
46099,67,69,69,LIFE OF OTHO.,NaN

Warning: total number of rows (46100) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
ents= pd.read_csv("/content/drive/MyDrive/historical_NER.csv")

In [ ]:
ents = ents.rename(columns={"sentence":"sent_lim"})

In [ ]:
ents

,Unnamed: 0,entity_text,label,score,sent_lim
0,0,Sossius Senecio,pers,0.924037,"I. As in books on geography, Sossius Senecio, ..."
1,1,Scythia,loc,0.997144,"I. As in books on geography, Sossius Senecio, ..."
2,2,Parallel Lives,pers,0.875612,"I. As in books on geography, Sossius Senecio, ..."
3,3,Lykurgus,pers,0.999696,When I had written the lives of Lykurgus the l...
4,4,Numa,pers,0.999694,When I had written the lives of Lykurgus the l...
...,...,...,...,...,...
73986,73986,Project,work,0.714812,This website includes information about Projec...
73987,73987,Gutenberg,pers,0.997368,This website includes information about Projec...
73988,73988,Project,work,0.567804,This website includes information about Projec...
73989,73989,Gutenberg,pers,0.995120,This website includes information about Projec...
73990,73990,Foundation,work,0.985375,This website includes information about Projec...

In [ ]:
merged_df_inner = pd.merge(sents, ents, on='sent_lim', how='inner')

In [ ]:
merged_df_inner = merged_df_inner.drop(columns={"Unnamed: 0.1","Unnamed: 0_x","X","Unnamed: 0_y"})

In [ ]:
pd.DataFrame(merged_df_inner['entity_text'].value_counts())

             count
entity_text
Alexander    41048
Antonius     34440
Pompeius     28654
Sulla        20689
Cicero       20314
...            ...
v. 5             1
Megalesia        1
29, c. 10        1
c. 84            1
105 Cn.          1

[9901 rows x 1 columns]

In [ ]:
merged_df_inner.to_csv("/content/drive/MyDrive/DaD_2026/bert_ner.csv")

,Title,sent_lim,entity_text,label,score
0,LIFE OF THESEUS.,"I. As in books on geography, Sossius Senecio, ...",Sossius Senecio,pers,0.924037
1,LIFE OF THESEUS.,"I. As in books on geography, Sossius Senecio, ...",Scythia,loc,0.997144
2,LIFE OF THESEUS.,"I. As in books on geography, Sossius Senecio, ...",Parallel Lives,pers,0.875612
3,LIFE OF THESEUS.,When I had written the lives of Lykurgus the l...,Lykurgus,pers,0.999696
4,LIFE OF THESEUS.,When I had written the lives of Lykurgus the l...,Numa,pers,0.999694
...,...,...,...,...,...
416464,LIFE OF OTHO.,This website includes information about Projec...,Project,work,0.714812
416465,LIFE OF OTHO.,This website includes information about Projec...,Gutenberg,pers,0.997368
416466,LIFE OF OTHO.,This website includes information about Projec...,Project,work,0.567804
416467,LIFE OF OTHO.,This website includes information about Projec...,Gutenberg,pers,0.995120
416468,LIFE OF OTHO.,This website includes information about Projec...,Foundation,work,0.985375

In [ ]:
import pandas as pd